Fixes #4637
iterative/dvc pull request #4670
Opened 2020-10-06 18:00 UTC by musa-atlihan

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2020-10-07 02:40 UTC, pmrowla requested changes
Looks like this is related to https://bugs.python.org/issue40358 `Path.relative_to` behaves differently than `os.path.relpath` in this situation

The changes in this PR do resolve the original bug, but I think it would be better for us to catch the `ValueError` in `PathInfo.relative_to` when we call the parent (python) `relative_to` function, and fallback to `os.path.relpath` there
https://github.com/iterative/dvc/blob/15b1e7072bf4c133a640507f59011d32501a968f/dvc/path_info.py#L227

that way we won't end up running into this same bug elsewhere in DVC

2020-10-07 02:40 UTC, pmrowla commented on dvc/stage/cache.py
> +from pathlib import Path
```suggestion
```

(see related comment below)

2020-10-07 02:40 UTC, pmrowla commented on dvc/stage/cache.py
> +            rel = Path(os.path.relpath(src, from_remote.path_info))
```suggestion
            rel = PathInfo(os.path.relpath(src, from_remote.path_info))
```

DVC `PathInfo` inherits from python's `PurePath` and should be preferred here

2020-10-08 11:45 UTC, musa-atlihan commented
thank you for the review @pmrowla ! I will update and push now.

2020-10-10 01:39 UTC, pmrowla commented
@musa-atlihan have you looked into trying my other suggestion regarding fixing `PathInfo.relative_to` in general (so that we handle this issue everywhere in DVC and not just this specific run cache bug)?

2020-10-10 09:13 UTC, musa-atlihan commented
@pmrowla , I pushed for the `PathInfo.relative_to` fix, could you check?

2020-10-12 06:18 UTC, pmrowla commented on dvc/stage/cache.py
> +            rel = PathInfo(os.path.relpath(src, from_remote.path_info))
I think this change is no longer needed after the fix in `path_info.py`, @musa-atlihan can you try reverting this and then confirm that `pull --run-cache` works as expected?

2020-10-19 08:53 UTC, merged

2020-10-19 08:53 UTC, pmrowla commented
Thank you for the PR @musa-atlihan! 🙏