test: allow selectively running tests for remotes
iterative/dvc pull request #4920
Opened 2020-11-20 09:30 UTC by skshetry

Some of the tests are run by default, other requires
`--enable-{remote}` to run. The remotes that are run by default
also have a `--disable-{remote}` flag. All of the remotes can be
enabled using `--all` flag.

To use this functionality in the fixture,
`test_config` fixture has to be used and requires to call
`test_config.requires(remote)`.
In an individual test, you can simply use `pytest.mark.remote`
to make them skip or run.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2020-11-20 09:31 UTC, skshetry commented on tests/conftest.py
> +    "http": True,
The `True` remotes will always run by default. To disable them, you can use `--disable-http` for example.

2020-11-20 09:32 UTC, skshetry commented on tests/conftest.py
> +    "azure": False,
The `False`/`disabled` remotes does not run on normal `pytest .` cases. You have to either enable all of the remotes, with `--all` or enable some of them by using `--enable-azure`, for example.

2020-11-20 09:33 UTC, skshetry commented on tests/remotes/gdrive.py
> +    test_config.requires("gdrive")
To enable this feature on a fixture level, you need to use `test_config` and call `test_config.requires(remote) to skip them or run them.

2020-11-20 09:34 UTC, skshetry commented on tests/unit/dependency/test_hdfs.py
> +@pytest.mark.hdfs
On an individual test level, you can use this feature with `pytest.mark.{remote}` marker.

2020-11-20 09:36 UTC, skshetry commented
### Please make sure it works on your end too while reviewing

2020-11-20 18:42 UTC, pared approved these changes

2020-11-20 21:12 UTC, efiop commented on tests/remotes/s3.py
> +    test_config.requires("s3")
Might want to have --disable/enable for `s3` and `real_s3` separately in the future. But for now this will do.

2020-11-20 21:17 UTC, efiop requested changes
Hm, from the first try:
```
(dvc-3.8.3) ➜  dvc git:(pytest-flags) ✗ pytest -mtests                                                                                                                                                                        
====================================================== test session starts ======================================================                                                                                             
platform linux -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1                                                                                                                                                         
rootdir: /home/efiop/git/skshetry/dvc                                                                                                                                                                                         
plugins: tap-3.1, openfiles-0.5.0, xdist-1.32.0, leaks-0.3.1, mock-1.11.2, lazy-fixture-0.6.3, cov-2.8.1, pyfakefs-4.1.0, docker-0.7.2, flaky-3.6.1, timeout-1.3.4, forked-1.1.3                                              
collected 1959 items / 1959 deselected                                                                                                                                                                                        
                                                                                                                                                                                                                              
======================================================= warnings summary ========================================================                                                                                             
/home/efiop/.pyenv/versions/3.8.3/envs/dvc-3.8.3/lib/python3.8/site-packages/boto/plugin.py:40                                                                                                                                
  /home/efiop/.pyenv/versions/3.8.3/envs/dvc-3.8.3/lib/python3.8/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp                                                                                                                                                                                                                
                                                                                                                                                                                                                              
-- Docs: https://docs.pytest.org/en/stable/warnings.html                                                                                                                                                                      
============================================== 1959 deselected, 1 warning in 1.66s ==============================================                                                                                             
```
if I use `--enable-s3`, i get:
```
(dvc-3.8.3) ➜  dvc git:(pytest-flags) ✗ pytest -mtests --enable-s3
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]  
pytest: error: unrecognized arguments: --enable-s3                
  inifile: None                                                   
  rootdir: /home/efiop/git/skshetry/dvc                                                                                            
```
but with `--disable-s3` it swallows it:
```
(dvc-3.8.3) ➜  dvc git:(pytest-flags) ✗ pytest -mtests --disable-s3                                                                                                                                                           
====================================================== test session starts ======================================================                                                                                             
platform linux -- Python 3.8.3, pytest-6.0.1, py-1.9.0, pluggy-0.13.1                                                                                                                                                         
rootdir: /home/efiop/git/skshetry/dvc                                                                                                                                                                                         
plugins: tap-3.1, openfiles-0.5.0, xdist-1.32.0, leaks-0.3.1, mock-1.11.2, lazy-fixture-0.6.3, cov-2.8.1, pyfakefs-4.1.0, docker-0.7.2, flaky-3.6.1, timeout-1.3.4, forked-1.1.3                                              
collected 1959 items / 1959 deselected                                                                                                                                                                                        
                                                                                                                                                                                                                              
======================================================= warnings summary ========================================================                                                                                             
/home/efiop/.pyenv/versions/3.8.3/envs/dvc-3.8.3/lib/python3.8/site-packages/boto/plugin.py:40                                                                                                                                
  /home/efiop/.pyenv/versions/3.8.3/envs/dvc-3.8.3/lib/python3.8/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp                                                                                                                                                                                                                
                                                                                                                                                                                                                              
-- Docs: https://docs.pytest.org/en/stable/warnings.html                                                                                                                                                                      
============================================== 1959 deselected, 1 warning in 3.01s ==============================================                                                                                             
```
am I missing something?

2020-11-21 01:21 UTC, skshetry commented
> Hm, from the first try:
> ```
> (dvc-3.8.3) ➜  dvc git:(pytest-flags) ✗ pytest -mtests   
> ```      
                                                                                                                                                               
@efiop, you must be confusing it with `python -m tests`. For pytest, `-m tests` runs only tests that have `tests` marker which there are none. Please do `python -m tests` or just `pytest`.                                                                                                                                                                                                                                                    

> if I use `--enable-s3`, i get:

`s3` is enabled by default, so I only provided disabling flag w/ `--disable-s3`. Similarly, for `hdfs`, it's disabled by default and only has `--enable-hdfs` flag. I thought it might be confusing to provide no-op flags.

2020-11-21 02:11 UTC, efiop commented
@skshetry Oh lol, you are right, that was a typo :man_facepalming: :man_facepalming: :man_facepalming: Though, using `--enable-s3` still throws:
```
(dvc-3.8.3) ➜  dvc git:(pytest-flags) ✗ python -mtests --enable-s3 
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]  
py.test: error: unrecognized arguments: --enable-s3                
  inifile: None                                                    
  rootdir: /home/efiop/git/skshetry/dvc                            
```
seems like it should be handled more gracefully. Swallowing --enable for a remote that is already enabled seems like a reasonable thing. WDYT?

2020-11-23 03:21 UTC, skshetry commented
> seems like it should be handled more gracefully. Swallowing --enable for a remote that is already enabled seems like a reasonable thing. WDYT?

I'm not a fan of that, but I see your point that it might not always be clearer on what is enabled or disabled by default.

We might not be able to prevent `--enable-s3 --disable-s3` cases as `pytest` does not allow anything fancy as "mutually exclusive". I'll just make them as a no-op flag.

2020-11-23 04:16 UTC, efiop approved these changes
:fire:

2020-11-23 05:58 UTC, merged