* [ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
iterative/dvc pull request #4936
Opened 2020-11-22 13:45 UTC by kgritesh

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2020-11-22 23:34 UTC, efiop commented on dvc/tree/hdfs.py
> +
```suggestion
```

2020-11-22 23:35 UTC, efiop approved these changes
Thank you so much @kgritesh! :pray:

2020-11-22 23:36 UTC, efiop commented
@kgritesh Btw, please go to https://github.com/settings/emails and add the email that you've used to create your commit. Right now github is not able to link your commits to your github profile.

2020-11-23 03:10 UTC, skshetry requested changes
This still does not fix the issue. Please see this [log on the Actions](https://github.com/iterative/dvc/pull/4936/checks?check_run_id=1439560851#step:7:4036).

2020-11-23 03:15 UTC, efiop commented
Good catch @skshetry ! :pray:

Closing this, since there is clearly a lot more work to be done and @jwokaty has already been working on a correct fix.

2020-11-23 03:15 UTC, closed without merging