Added configuration option for not doing chunked upload for HTTP remotes
iterative/dvc pull request #6117
Opened 2021-06-04 15:47 UTC by scotty3005

Changes to be committed:
	modified:   dvc/config_schema.py
	modified:   dvc/fs/http.py

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2021-06-05 03:13 UTC, karajan1001 requested changes

2021-06-05 03:13 UTC, karajan1001 commented on dvc/fs/http.py
> +        if response.status_code not in (200, 201):
Duplicated code with what in `_upload_fobj_chunked` maybe we can move them to `_upload_fobj`

2021-06-05 03:13 UTC, karajan1001 commented on dvc/fs/http.py
> +            if r.ok or r.status_code == 404:
Would this cause some problems when the server was actually not found (404). Some additional check are needed.

2021-06-05 03:14 UTC, karajan1001 commented
Thanks for your contributions, so this PR is related to #6118 ? I recommend You can add a link to it.

2021-06-05 03:17 UTC, karajan1001 reviewed
And, some tests are needed for this PR.

2021-06-05 14:17 UTC, scotty3005 commented
Hi, thanks for the feedback. I am willing to work on implementing some tests where needed. However I would be glad if I could have some help as it is not clear to me how to test remotes.

2021-06-07 15:48 UTC, efiop commented
I also wonder if https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/http.py is already able to do what you need. We are migrating to fsspec and will be considering replacing our http implementation with their soon, so might be a good time to give it a shot.

2021-06-08 08:48 UTC, isidentical commented
It seems like `open()` on `HTTPFileSystem` is read-only;
https://github.com/intake/filesystem_spec/blob/61ec18fb0a77d3a524a6b2d72340af3748c5bf2a/fsspec/implementations/http.py#L279-L280

2021-07-18 22:35 UTC, efiop commented
@scotty3005 Note that your PR now includes perm changes to a lot of files, which obviously shouldn't be there. There is something wrong with your environment, most likely.

2021-07-19 08:12 UTC, scotty3005 commented
Hey @efiop, yes I noted the issue with the changes. I do not what happen. W.r.t. the authorship I believe it is because I worked from two different machines, and forgot to set the local user name and email. 
 In the meanwhile that you guys do the migration, would you prefer to close this and me to resubmit a cleaner PR (correcting the changes and authorship)?

2021-07-19 22:13 UTC, efiop commented
@scotty3005 As @karajan1001 noted, the current logic will cause problems for other servers, so we need more research here to see if we can actually detect this and handle the fallback properly. Unfortunately, I would probably recommend closing this PR for now and going through the research to implement proper logic. 🙁

2021-07-20 06:49 UTC, scotty3005 commented
Hey @efiop, sure I understand. I will close this and keep maintaining the fork for my particular use case. Thanks for the time you guys dedicated to this issue. I am looking forward to contribute to DVC in other occasions.

2021-07-20 06:49 UTC, closed without merging