import: error message when imported file does not exist
iterative/dvc pull request #6240
Opened 2021-06-28 15:25 UTC by mmeendez8

* [ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

This is a quite simple simplest solution for the problem that avoids a larger refactor of the actual code. 

I just extended [test_import_non_existing](https://github.com/iterative/dvc/blob/master/tests/func/test_import.py#L349) with a simple test that tries to import a non-existent file from dvc repo so I could test this. 

```python
def test_import_non_existing(erepo_dir, tmp_dir, dvc):
    with pytest.raises(FileNotFoundError):
        tmp_dir.dvc.imp(os.fspath(erepo_dir), "invalid_output")

    # https://github.com/iterative/dvc/pull/2837#discussion_r352123053
    with pytest.raises(FileNotFoundError):
        tmp_dir.dvc.imp(os.fspath(erepo_dir), "/root/", "root")

    with pytest.raises(NoOutputInExternalRepoError):
        dvc.imp("https://github.com/iterative/dvc.git", "non-existent")
```

I am not adding the test to the PR since it requires to download a GH repo and I am not sure about how would you handle this specific case (I have seen other tests where you locally create a repo and add some commits but I think that does not adjust to this)

2021-06-28 16:01 UTC, pmrowla requested changes
Thanks for the PR!

`test_import_non_existing` should be updated to check for whatever exception is raised after these changes in all of the test cases. Any time we are importing, we are importing from an "external" repo, external doesn't only apply to remote git URLs.

The `erepo_dir` pytest fixture points to a separate repo that is used as the external repo for test cases, and can be used as such in `test-import.py` (so we don't have to test with github URLs)

2021-06-28 16:43 UTC, mmeendez8 commented on dvc/dependency/repo.py
> +                if not os.path.exists(repo.url):
Oh thanks for that explanation! :+1:  I understand what you mean. Nevertheless when `repo` is a remote git URL, it is cloned to a temporal location which is unknown for the user https://github.com/iterative/dvc/issues/6207#issuecomment-865933945  which results in an error message that is quite hard to interprete. That's the main reason behind that if condition.

2021-06-29 00:36 UTC, pmrowla commented on dvc/dependency/repo.py
> +                if not os.path.exists(repo.url):
I understand that, but we can replace cloned temporary repo path in the error message with the original git URL.

In the exception that is re-raised here, we should replace `str(repo)` with `self.def_repo[self.PARAM_URL]` to display the original imported location (which may be a git URL or a local path to a different DVC repo).

2021-06-30 06:37 UTC, karajan1001 approved these changes

2021-06-30 06:49 UTC, pmrowla approved these changes

2021-06-30 06:49 UTC, merged

2021-06-30 06:49 UTC, pmrowla commented
Thanks again for the PR!