machine:remove help text for irrelevant commands (#6940)
iterative/dvc pull request #6950
Opened 2021-11-10 08:39 UTC by karajan1001

fix: #6940

`--global/system/project/local` help message are in some irrelevant
command `status`, `ssh`, `create`, `destroy`. These commands are more
related to running instances rather than `machine config`, level
options didn't work for them.

1. Remove `--global/system/project/local` options in `status`, `ssh`,
   `create`, `destroy`.
2. Add a test for it.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2021-11-10 15:01 UTC, dberenbaum approved these changes

2021-11-15 08:40 UTC, karajan1001 commented
@Mergifyio rebase

2021-11-17 06:09 UTC, pmrowla approved these changes

2021-11-17 06:10 UTC, pmrowla requested changes

2021-11-17 06:10 UTC, pmrowla commented on tests/unit/command/test_machine.py
> +def test_eename(tmp_dir, scm, dvc):
```suggestion
def test_rename(tmp_dir, scm, dvc):
```

Looks like a typo got committed here?

2021-11-17 07:19 UTC, pmrowla approved these changes
the typo commit can be squashed before merging this

2021-11-17 08:25 UTC, merged