[WIP] exp show: show exp when checkpoint is running(#7329)
iterative/dvc pull request #7349
Opened 2022-02-04 10:43 UTC by karajan1001

fix: #7329
In a previous PR, we introduce a bug which use `HEAD` as the workspace
commit, while if there is a checkpoint is running, the `HEAD` is
actually changing all the time, we should use
`refs/exps/exec/EXEC_BASELINE` instead.

A test is needed for this PR.

1. replace the default `HEAD` in `exp show` with `fix_exp_head`.
2. modify a functional test to simulate the running conditions.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2022-02-08 05:03 UTC, pmrowla requested changes
So the actual cause of this bug is that we don't handle fixing `HEAD` in `iter_revs`:

https://github.com/iterative/dvc/blob/e430693fc81b0ba27131756039e3191d0b93d83d/dvc/scm.py#L157

I think what we should really do for this is to make `dvc.scm.resolve_rev()` use `fix_exp_head`, and get rid of all of the other calls to `fix_exp_head` from elsewhere in DVC, otherwise we will probably keep running into this type of bug in the future.

and then we can just have one test for `scm.resolve_rev()` that does the same thing as:

https://github.com/iterative/dvc/blob/e430693fc81b0ba27131756039e3191d0b93d83d/tests/func/experiments/test_experiments.py#L625-L636



At some point what we really want is to make `scm.resolve_rev()` use `fix_exp_head`, and get rid of all of the other `fix_exp_head` calls everywhere else in DVC,

2022-02-08 10:11 UTC, karajan1001 commented
Currently, `scmrepo` is decoupled with this `experiments` related setting? Maybe it is better to put this logic in `dvc/repo/experiments/utils.py` instead of `scmrepo`. BTW, the import logic of `dvc/repo/experiments/utils.py` and `dvc/scm.py` is a little bit tricky, sometimes` utils.py` depends on something from `scm.py` sometimes the dependency comes from the opposite direction.

And besides this, I don't know if there are any conditions that we need to resolve the current temp local `HEAD` instead of the `exp_head`?

2022-02-08 10:40 UTC, pmrowla commented
> Currently, `scmrepo` is decoupled with this `experiments` related setting? Maybe it is better to put this logic in `dvc/repo/experiments/utils.py` instead of `scmrepo`. BTW, the import logic of `dvc/repo/experiments/utils.py` and `dvc/scm.py` is a little bit tricky, sometimes` utils.py` depends on something from `scm.py` sometimes the dependency comes from the opposite direction.

This does not belong in `scmrepo` for sure, `dvc.scm` is for scm/git behavior that is DVC specific (like this issue).

The main issue with keeping `fix_exp_head` separate from `dvc.scm.resolve_rev` is that this affects every DVC command (such as`dvc diff`), not just `exp` commands.

> And besides this, I don't know if there are any conditions that we need to resolve the current temp local `HEAD` instead of the `exp_head`?

In the event that we need the local head, we can just use `scm.get_ref("HEAD")` directly.

2022-02-09 04:06 UTC, karajan1001 commented
OK `dvc.scm.resolve_rev` (dvc/scm.py::resolve_rev) is different from `dvc.scm.resolve_rev` (dvc("Repo").scm("Git")::resolve_rev)
quite confusing.

2022-02-15 13:17 UTC, pmrowla approved these changes

2022-02-15 13:17 UTC, merged