exp queue: Add two command `queue remove` and `queue kill`
iterative/dvc pull request #7721
Opened 2022-05-10 11:28 UTC by karajan1001

fix: #7591

1. Add a new command `dvc queue`
2. Add two sub-command `dvc queue remove` and `dvc queue kill`
3. Add a unit test to test them

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

wait for #7714

2022-05-10 11:30 UTC, karajan1001 commented
Current UI

```bash
$ dvc queue --help
usage: dvc queue [-h] [-q | -v] {remove,kill} ...

Commands to manage dvc task queue.
Documentation: <https://man.dvc.org/queue>

positional arguments:
  {remove,kill}  Use `dvc queue CMD --help` to display command-specific help.
    remove       Remove experiments in queue
    kill         Kill experiments in queue

optional arguments:
  -h, --help     show this help message and exit
  -q, --quiet    Be quiet.
  -v, --verbose  Be verbose.

$ dvc queue remove --help
usage: dvc queue remove [-h] [-q | -v] [--all] [<experiment> [<experiment> ...]]

Remove experiments in queue
Documentation: <https://man.dvc.org/queue/remove>

positional arguments:
  <experiment>   Experiments in queue to remove.

optional arguments:
  -h, --help     show this help message and exit
  -q, --quiet    Be quiet.
  -v, --verbose  Be verbose.
  --all          Remove all experiments in queue.

$ dvc queue kill --help
usage: dvc queue kill [-h] [-q | -v] [<experiment> [<experiment> ...]]

Kill experiments in queue
Documentation: <https://man.dvc.org/queue/kill>

positional arguments:
  <experiment>   Experiments in queue to kill.

optional arguments:
  -h, --help     show this help message and exit
  -q, --quiet    Be quiet.
  -v, --verbose  Be verbose.
```

2022-05-13 15:47 UTC, dberenbaum commented
Should I wait for #7714 before testing this?

2022-05-16 02:33 UTC, pmrowla requested changes
Just a couple minor things, LGTM otherwise

2022-05-16 02:33 UTC, pmrowla commented on dvc/commands/queue/kill.py
> +    """kill exp task in queue"""
```suggestion
    """Kill exp task in queue."""
```

2022-05-16 02:33 UTC, pmrowla commented on dvc/commands/queue/remove.py
> +        removed = ",".join(removed_list)
```suggestion
        removed = ", ".join(removed_list)
```

2022-05-16 02:33 UTC, pmrowla commented on dvc/commands/queue/remove.py
> +    """remove exp in queue"""
```suggestion
    """Remove exp in queue."""
```

2022-05-16 02:33 UTC, pmrowla commented on dvc/commands/queue/__init__.py
> +    fix_plumbing_subparsers(queue_subparsers)
```suggestion
```

This call shouldn't be needed since there's no subcommands we want to hide right now

2022-05-16 04:43 UTC, pmrowla commented
@karajan1001 there's a linting error now (unused import), just fix that and then squash your commits and this can be merged

2022-05-16 07:50 UTC, karajan1001 commented
Just wondered why always got some tests failed?

2022-05-16 08:01 UTC, pmrowla commented
The `exp show` tests are flaky because they haven't been updated to properly work with the celery changes.

2022-05-17 12:16 UTC, karajan1001 commented
@dberenbaum Could you please give help on the product side?

2022-05-17 12:32 UTC, pmrowla commented
I think it may be easier for us to just merge these PRs into the dev branch so that testing can be done w/all of the commands available, and then iterate/fix bugs from there

2022-05-17 17:23 UTC, dberenbaum commented
> I think it may be easier for us to just merge these PRs into the dev branch so that testing can be done w/all of the commands available, and then iterate/fix bugs from there

How soon do you expect to merge? If it's in the next couple days, I will wait. Otherwise, I'll try to look at what I can now.

2022-05-18 02:33 UTC, karajan1001 commented
> > I think it may be easier for us to just merge these PRs into the dev branch so that testing can be done w/all of the commands available, and then iterate/fix bugs from there
> 
> How soon do you expect to merge? If it's in the next couple days, I will wait. Otherwise, I'll try to look at what I can now.

I think we can wait in the next couple of days.

2022-05-18 02:54 UTC, merged