exp init: don't add outs to .gitignore
iterative/dvc pull request #7740
Opened 2022-05-12 19:54 UTC by dberenbaum

Addresses https://github.com/iterative/dvc/issues/5802#issuecomment-1115709992 by not adding to `.gitignore` during `exp init` since it breaks for subdirectories. Adding to `.gitignore` is still done on `exp run` / `repro`.

2022-05-13 07:55 UTC, daavoo approved these changes
Out of the scope of the P.R. but was wondering why exp init doesn't use `stage.add`?

2022-05-13 08:01 UTC, daavoo requested changes
Need to update tests:

```
assert scm.is_tracked(".gitignore")
```

2022-05-13 12:26 UTC, dberenbaum commented
> Need to update tests:

Sorry, forgot to remove those lines before before pushing. It should pass now.

> Out of the scope of the P.R. but was wondering why exp init doesn't use `stage.add`?

@skshetry can answer, but I'm guessing from https://github.com/iterative/dvc/blob/37a20e922f065dc7c2814e56d9d8ed1c5ed97b6f/dvc/repo/experiments/init.py#L254 that it's because we need to modify some things like disabling output.

2022-05-14 10:27 UTC, skshetry commented
> Out of the scope of the P.R. but was wondering why exp init doesn't use `stage.add`?

Previously, we used to ask for confirmation in an interactive mode before creating the stage. `exp init` also auto-stages `dvc.yaml` and `params.yaml` file which `stage add` does not do by default (unless `core.autostage=true`).

Now, this PR is another reason for not using `stage add`. `stage add` also auto-commits the file, whereas `dvc exp init` may require more processing before committing the file (if not now, in the future anyway), so I don't think `stage add` is a good fit.

We could extend `stage add` for sure, but dumping stages are complex and can be done in a lot of ways, I don't want to overcomplicate it with all the complexities that may be introduced by `exp init`.

2022-05-16 12:40 UTC, dberenbaum commented
I'm fine with keeping the scope of this PR as small as possible for now. Could one of you please review now that the tests have been fixed?

2022-05-16 12:48 UTC, skshetry commented
@dberenbaum, I am a bit hesitant to change the behaviour here, although no strong opinion. I'm okay with:

1. either git-ignoring what we can and leave the rest to `repro`,
2. git-ignoring by traversing upwards (it's going to require some changes in scmrepo, so definitely not a straightforward fix),
3. or, generate intermediate directories.

DVC expects the path to the output to exist in a lot of places (more in relation to stage's working directory, but usually that's where `.dvc` files are created by default). WDYT of 1 and 3, or a combination of both options?

2022-05-16 16:58 UTC, dberenbaum commented
@skshetry Can you explain why you are hesitant (and why dvc should generate `.gitignore` files at all when [creating stages](https://github.com/iterative/dvc/issues/5802#issuecomment-1116565862))?

I opened a PR for 3 in https://github.com/iterative/dvc/pull/7751. That would solve the immediate issue, although the rationale for adding to `.gitignore` during stage creation is still unclear to me.

2022-06-07 12:18 UTC, skshetry commented
> @skshetry Can you explain why you are hesitant (and why dvc should generate `.gitignore` files at all when [creating stages](https://github.com/iterative/dvc/issues/5802#issuecomment-1116565862))?
> 
> I opened a PR for 3 in #7751. That would solve the immediate issue, although the rationale for adding to `.gitignore` during stage creation is still unclear to me.

The only concern is that the users may `git add` accidentally in between, the `.gitignore` prevents that.

2022-06-07 19:55 UTC, dberenbaum commented
Good point @skshetry. I'll close this one for now since the issue was addressed in #7752. We can come back to it if needed.

2022-06-07 19:55 UTC, closed without merging