plots templates: change ui to not dump to file
iterative/dvc pull request #8129
Opened 2022-08-12 20:16 UTC by dberenbaum

Fixes #7944 

This was bothering me, so I went ahead and updated the `plots templates` UI. I went with the suggestion from @pared to remove `-o` since it seemed unnecessary now that you don't need them in `.dvc/plots`.

It is a breaking change, but the feature is pretty new and obscure and unlikely to be part of automation.

2022-08-17 11:08 UTC, daavoo commented on tests/unit/command/test_plots.py
> +        pytest.raises(ValueError)
The custom exception was not really being tested. Need to:

```suggestion
    else:
        with pytest.raises(ValueError):
            cmd.run()
```

2022-08-17 11:09 UTC, daavoo commented on dvc/commands/plots.py
> +                raise ValueError(f"Unexpected template: {target}.")
Just 💅 (`from dvc.exceptions import InvalidArgumentError`):
 
```suggestion
                raise InvalidArgumentError(f"Unexpected template: {target}.")
```

2022-08-19 06:35 UTC, daavoo approved these changes

2022-08-22 09:23 UTC, pared requested changes

2022-08-22 09:23 UTC, pared commented on dvc/commands/plots.py
> +                        ui.write(template.DEFAULT_CONTENT)
```suggestion
                        ui.write(json.dumps(template.DEFAULT_CONTENT))
```

If we just provide the dict, printed string will wrap fields in single quote which standard json library wont accept.
For example:
```
dvc plots templates confusion | python -m json.tool
```
will fail

2022-08-23 14:28 UTC, pared approved these changes

2022-08-23 14:40 UTC, pared commented on dvc/commands/plots.py
> +                        ui.write(json.dumps(template.DEFAULT_CONTENT))
Oops, my bad. Sorry @dberenbaum

2022-08-23 16:14 UTC, dberenbaum commented on dvc/commands/plots.py
> +                    ui.write(template.DEFAULT_NAME)
No, it's specifically for built-in templates. The only way DVC could even know about custom templates is if they are in `.dvc/plots`, and we are moving away from being reliant on that location (it's really only needed for backwards compatibility).

2022-08-28 22:46 UTC, merged