plots: allow top-level strings
iterative/dvc pull request #8482
Opened 2022-10-27 17:19 UTC by dberenbaum

Follow up to https://github.com/iterative/dvc/pull/8412 to allow for entering file paths as strings instead of dict keys:

```diff
plots:
+  - path/to/file
-  - path/to/file:
```

Some of the JSON output tests are failing in `tests/integration/plots/test_plots.py`. @pared When you have a chance, could you take a look and see if you have any idea why?

2022-10-27 17:20 UTC, dberenbaum commented
Schema changes are in https://github.com/iterative/dvcyaml-schema/tree/top-level-plot-str

2022-10-27 17:32 UTC, dberenbaum commented
Docs PR: https://github.com/iterative/dvc.org/pull/4081

2022-10-31 15:04 UTC, pared requested changes

2022-10-31 15:04 UTC, pared commented on dvc/repo/plots/__init__.py
> +            print(dvcfile_defs_dict)
this is the cause :)

2022-10-31 15:04 UTC, pared commented on dvc/repo/plots/__init__.py
> +            print(dvcfile_defs_dict)
```suggestion

```

2022-10-31 15:41 UTC, dberenbaum commented on dvc/repo/plots/__init__.py
> +            print(dvcfile_defs_dict)
😬 Sorry about that!

2022-10-31 16:00 UTC, pared approved these changes

2022-11-03 19:18 UTC, dberenbaum commented
@pared Could you merge when you have a chance? I don't have permission.

2022-11-04 04:09 UTC, merged

2022-11-04 04:14 UTC, skshetry commented
> @pared Could you merge when you have a chance? I don't have permission.

@dberenbaum, please check. I have fixed it (`all` had `write` permissions but somehow `dvc-all` had lesser permissions which I have switched).

2022-11-04 14:11 UTC, dberenbaum commented
Thanks @skshetry. TBH I don't mind not having merge permissions (it might be a good separation of duties) but I think `dvc-all` would need `maintain` privileges to merge to main. Looks like I'm still blocked right now from merging.

2022-11-04 14:17 UTC, skshetry commented
@dberenbaum, `Write` does have merge permissions. See https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role.

What you may not have is
>  Merge pull requests on protected branches, even if there are no approving reviews

which requires Admin permissions.