Make temp dir executed checkpoint experiment return result to workspace.
iterative/dvc pull request #8668
Opened 2022-12-07 13:09 UTC by karajan1001

fix: #8612
For checkpoint experiments in some cases, users might want to give it an early stopping to reduce variance.  But currently, if we interrupt/kill the experiment it will be marked as failed, and all of the completed checkpoints will be removed as we clean up all the running directly after the process failed.

1. We raise CheckpointKilledError instead of StageCmdFailed error if at least one checkpoint had been committed.
2. Temp_dir executor will continue collecting data if the Checkpoint stage was interrupted.
3. Raise warnings if a checkpoint stage was incomplete and the other stages were not forwarded.
4. Add a new functional test for this

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

2022-12-08 02:12 UTC, pmrowla requested changes

2022-12-08 17:48 UTC, dberenbaum commented on dvc/repo/reproduce.py
> +            broken = True
I don't think there's a way for DVC to continue to downstream stages from checkpoints at all right now, so I'd agree we don't need this warning (or at least we don't need "remaining stages in pipeline will not be reproduced").

2022-12-16 02:27 UTC, karajan1001 commented
![image](https://user-images.githubusercontent.com/6745454/208007905-40954943-c043-4343-89c5-5e09fdf67348.png)

2022-12-16 18:35 UTC, dberenbaum commented
@karajan1001 Maybe there is someone else in @iterative/dvc who can review while @pmrowla is out so we can get it merged?

2022-12-16 18:41 UTC, dberenbaum approved these changes
LGTM!

2022-12-20 03:22 UTC, karajan1001 commented
> @karajan1001 Maybe there is someone else in @iterative/dvc who can review while @pmrowla is out so we can get it merged?

One problem remained for the `--queue` experiments, it returns results at failure but with only a failed task, while all of the checkpoints are lost.

2022-12-26 08:02 UTC, pmrowla approved these changes

2022-12-26 12:40 UTC, merged

2022-12-27 19:34 UTC, dberenbaum commented
> One problem remained for the `--queue` experiments, it returns results at failure but with only a failed task, while all of the checkpoints are lost.

@karajan1001 Is this still an issue?

2022-12-30 07:14 UTC, karajan1001 commented
> > One problem remained for the `--queue` experiments, it returns results at failure but with only a failed task, while all of the checkpoints are lost.
> 
> @karajan1001 Is this still an issue?

This behavior is different from `--temp` in which we return completed checkpoint results even if the tasks failed. I think the `--temp` behavior is more reasonable.