exp save: always dvc commit changes
iterative/dvc pull request #8691
Opened 2022-12-13 20:27 UTC by dberenbaum

See https://github.com/iterative/dvclive/issues/408

2022-12-13 21:47 UTC, daavoo commented on dvc/repo/experiments/save.py
> +        executor.info, force=True, include_untracked=include_untracked
👍 good to decouple from the other `force`

2022-12-13 21:47 UTC, daavoo approved these changes

2022-12-14 11:49 UTC, daavoo requested changes
2 different tests are failing in 2 different envs. Not sure why

https://github.com/iterative/dvc/actions/runs/3694378088/jobs/6255496899#step:5:952
https://github.com/iterative/dvc/actions/runs/3694378088/jobs/6255497444#step:5:985

2022-12-14 12:44 UTC, dtrifiro commented
I'd wait for for #8690 before taking this on

2022-12-14 13:25 UTC, dberenbaum commented
@dtrifiro Should I close and we can discuss/incorporate into that PR?

2022-12-14 13:32 UTC, dtrifiro commented
Yeah, that'd be best.

2022-12-14 13:32 UTC, closed without merging